FROM alpine:latest as build

#Define build argument for version
ARG VERSION=1.23.3

RUN apk update && \
    apk add --no-cache build-essential \
        build-base \
        curl \
        jq \
        git \
        perl \
        sed \
        grep \
        tar \
        linux-headers \
        musl-dev \

RUN echo $VERSION

RUN set -x                                                                          && \
     cd /tmp                                                                        && \
     wget -q http://nginx.org/download/nginx-${VERSION}.tar.gz                      && \
     wget -q http://nginx.org/download/nginx-${VERSION}.tar.gz.asc                  && \
     tar -xvf nginx-${VERSION}.tar.gz

WORKDIR /tmp/nginx-${VERSION}

# Note: Alpine's configure might have slightly different options or require different flags for static linking.
# For example, --with-ld-opt="-static" might need adjustment or might not be directly supported in the same way.
# You might need to check Alpine's specific build recommendations for Nginx if you encounter issues.
# However, for typical Nginx compilation, the following should work or be easily adaptable.
RUN ./configure --with-ld-opt="-static" --with-http_sub_module                      && \
    make install                                                                    && \
    strip /usr/local/nginx/sbin/nginx

RUN ln -sf /dev/stdout /usr/local/nginx/logs/access.log                             && \
    ln -sf /dev/stderr /usr/local/nginx/logs/error.log


FROM scratch

# LABEL maintainer="Marcelo Lopez <marcelo.lopez@aeolabs.io>"

# Copy only necessary files from the build stage
# Alpine's /etc/passwd and /etc/group are minimal, so copying them is fine.
COPY --from=build /etc/passwd /etc/group /etc/
COPY --from=build /usr/local/nginx /usr/local/nginx
COPY nginx.conf /etc/nginx/nginx.conf
COPY index.html /usr/local/nginx/html/

#Change default stop signal from SIGTERM to SIGQUIT
STOPSIGNAL SIGQUIT

# Expose port
EXPOSE 80/tcp

# Define entrypoint and default parameters
ENTRYPOINT ["/usr/local/nginx/sbin/nginx"]
CMD ["-g", "daemon off;"]
